openapi: 3.0.3
info:
  title: Образовательная платформа Probujdenie
  description: API для образовательной платформы Probujdenie
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /api/v1/courses:
    $ref: './paths/public/courses.yaml'
  /api/v1/courses/{courseId}/sections:
    $ref: './paths/public/courses-courseId-sections.yaml'
  /api/v1/sections/{sectionId}/lectures:
    $ref: './paths/public/sections-sectionId-lectures.yaml'
  /api/v1/files/{fileId}:
    $ref: './paths/public/files-fileId.yaml'

  /student-secure/api/v1/courses/my-courses:
    $ref: './paths/student-secure/courses.my-courses.yaml'
  /student-secure/api/v1/courses/{courseId}/buy:
    $ref: './paths/student-secure/courses-courseId-buy.yaml'
  /student-secure/api/v1/exercises/{exerciseId}/submissions:
    $ref: './paths/student-secure/exercises-exerciseId-submit.yaml'
  /student-secure/api/v1/exercises/{exerciseId}:
    $ref: './paths/student-secure/exercises-exerciseId.yaml'

  /admin-secure/api/v1/courses:
    $ref: './paths/admin-secure/courses.yaml'
  /admin-secure/api/v1/courses/{id}:
    $ref: './paths/admin-secure/courses-courseId.yaml'
  /admin-secure/api/v1/files:
    $ref: './paths/admin-secure/files.yaml'
  /admin-secure/api/v1/files/{fileId}:
    $ref: './paths/admin-secure/files-fileId.yaml'
  /admin-secure/api/v1/courses/{courseId}/sections:
    $ref: './paths/admin-secure/courses-courseId-sections.yaml'
  /admin-secure/api/v1/sections/{sectionId}:
    $ref: './paths/admin-secure/sections-sectionId.yaml'
  /admin-secure/api/v1/sections/{sectionId}/lectures:
    $ref: './paths/admin-secure/sections-sectionId-lectures.yaml'
  /admin-secure/api/v1/lectures/{lectureId}:
    $ref: './paths/admin-secure/lectures-lectureId.yaml'
  /admin-secure/api/v1/lectures/{lectureId}/exercises:
    $ref: './paths/admin-secure/lectures-lectureId-exercises.yaml'
  /admin-secure/api/v1/exercises/{exerciseId}:
    $ref: './paths/admin-secure/exercises-exerciseId.yaml'


